import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Bar } from 'react-chartjs-2';
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, Tooltip, Legend } from 'chart.js';
import './styles.css';
ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend);
const api = import.meta.env.VITE_API_URL || 'http://localhost:8000/api/v1';

function App() {
  const [rooms, setRooms] = useState([]); const [readings, setReadings] = useState([]);
  const [alerts, setAlerts] = useState([]); const [report, setReport] = useState(null); const [message, setMessage] = useState('');
  const load = async () => { try { const [a,b,c,d] = await Promise.all(['rooms','readings','alerts','reports/summary'].map(x => fetch(`${api}/${x}`).then(r => r.json()))); setRooms(a); setReadings(b); setAlerts(c); setReport(d); } catch { setMessage('Não foi possível conectar à API. Inicie os serviços com Docker Compose.'); } };
  useEffect(() => { load(); }, []);
  const send = async (path, data, success) => { const res = await fetch(`${api}/${path}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(data) }); if (res.ok) { setMessage(success); load(); return true; } setMessage('Verifique os dados informados.'); return false; };
  const submitReading = async e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.target)); data.room_id=Number(data.room_id); data.kwh=Number(data.kwh); if (await send('readings', data, 'Consumo registrado e analisado.')) e.target.reset(); };
  const submitRoom = async e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.target)); data.expected_kwh=Number(data.expected_kwh); if (await send('rooms', data, 'Sala cadastrada.')) e.target.reset(); };
  const chart = { labels:(report?.by_room||[]).map(x=>x.room), datasets:[{label:'Consumo registrado (kWh)',data:(report?.by_room||[]).map(x=>x.kwh),backgroundColor:'#22a06b'},{label:'Esperado (kWh)',data:(report?.by_room||[]).map(x=>x.expected),backgroundColor:'#9bdcc0'}] };
  return <main><header><div><span className="brand">EcoWatt</span><p>Monitoramento acadêmico de consumo de energia</p></div><span className="ods">ODS 7.3</span></header><section className="intro"><h1>Consumo de energia sob controle</h1><p>Registre leituras simuladas, compare com o consumo esperado e identifique desperdícios.</p></section>{message && <p className="message">{message}</p>}<section className="metrics"><Metric title="Consumo total" value={`${report?.total_kwh?.toFixed(1)||0} kWh`}/><Metric title="Meta acumulada" value={`${report?.expected_kwh?.toFixed(1)||0} kWh`}/><Metric title="Economia possível" value={`${report?.estimated_savings_kwh?.toFixed(1)||0} kWh`}/><Metric title="Leituras excessivas" value={report?.excessive_readings||0}/></section><section className="grid"><article><h2>Consumo por sala</h2><Bar data={chart} options={{responsive:true,plugins:{legend:{position:'bottom'}}}}/></article><article><h2>Registrar consumo</h2><form onSubmit={submitReading}><label>Sala<select name="room_id" required><option value="">Selecione</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.name} ({r.expected_kwh} kWh)</option>)}</select></label><label>Data<input name="recorded_on" type="date" required/></label><label>Consumo em kWh<input name="kwh" type="number" step="0.01" min="0.01" required/></label><button>Registrar e analisar</button></form></article></section><section className="grid"><article><h2>Cadastro de sala</h2><form onSubmit={submitRoom}><label>Nome<input name="name" required/></label><label>Setor<input name="sector" required/></label><label>Responsável<input name="responsible" required/></label><label>Consumo esperado em kWh<input name="expected_kwh" type="number" step="0.01" min="0.01" required/></label><button>Cadastrar sala</button></form></article><article><h2>Alertas</h2>{alerts.length?<ul>{alerts.map(a=><li key={a.id}>{a.message}</li>)}</ul>:<p>Nenhum alerta gerado.</p>}<h2 className="spacing">Últimas leituras</h2><table><thead><tr><th>Data</th><th>kWh</th><th>Situação</th></tr></thead><tbody>{readings.slice(0,6).map(r=><tr key={r.id}><td>{r.recorded_on}</td><td>{r.kwh}</td><td className={r.status==='EXCESSIVO'?'bad':'good'}>{r.status}</td></tr>)}</tbody></table></article></section></main>;
}
function Metric({title,value}) { return <article className="metric"><span>{title}</span><strong>{value}</strong></article>; }
createRoot(document.getElementById('root')).render(<App/>);
